[project]
name = "task-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django-rest-framework>=0.1.0",
    "psycopg2>=2.9.11",
    "python-decouple>=3.8",
]
